import type { MarketOverview, Signal, SystemHealth } from "./types";

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();

export const MOCK_SIGNALS: Signal[] = [
  {
    id: "sig-001",
    instrument: "NIFTY",
    direction: "BULLISH",
    methodology: "SMC",
    state: "ACTIVE",
    score: 82,
    grade: "A",
    createdAt: minutesAgo(24),
    updatedAt: minutesAgo(3),
    entry: 24118.5,
    stopLoss: 24072.0,
    targets: [24185.0, 24240.0],
    riskReward: 2.9,
    coreSignal: [{ kind: "MSS", price: 24101.0, note: "Bullish MSS confirmed by displacement" }],
    confirmations: [
      { kind: "SWEEP", price: 24069.0, note: "Sell-side liquidity swept below prior day low" },
      { kind: "FVG_BULLISH", price: 24108.0, note: "Retest of bullish FVG" },
    ],
    conflicts: [],
    reasoningChain: [
      "Sell-side liquidity swept below the prior day low",
      "Bullish MSS confirmed on displacement",
      "Price retraced into the bullish FVG left by the displacement leg",
      "Entry taken on FVG retest with structure holding",
    ],
    dataQuality: "HIGH",
    decision: "MANUAL_ENTRY",
  },
  {
    id: "sig-002",
    instrument: "BANKNIFTY",
    direction: "BEARISH",
    methodology: "SMC",
    state: "CONFIRMED",
    score: 71,
    grade: "B",
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(1),
    entry: 51230.0,
    stopLoss: 51410.0,
    targets: [50920.0],
    riskReward: 1.7,
    coreSignal: [{ kind: "CHOCH", price: 51340.0, note: "Bearish CHoCH confirmed" }],
    confirmations: [{ kind: "ORDER_BLOCK_BEARISH", price: 51305.0, note: "Reaction from bearish order block" }],
    conflicts: [{ kind: "PREMIUM_DISCOUNT", price: 51230.0, note: "Price still in premium of HTF range" }],
    reasoningChain: [
      "Bearish CHoCH confirmed against prior bullish structure",
      "Reaction from an unmitigated bearish order block",
      "Still trading in premium of the higher-timeframe range — not yet in discount",
    ],
    dataQuality: "HIGH",
    decision: "REVIEW",
  },
  {
    id: "sig-003",
    instrument: "NIFTY",
    direction: "BULLISH",
    methodology: "SMC",
    state: "DEVELOPING",
    score: 54,
    grade: "C",
    createdAt: minutesAgo(6),
    updatedAt: minutesAgo(1),
    entry: null,
    stopLoss: null,
    targets: [],
    riskReward: null,
    coreSignal: [{ kind: "EQUAL_LOWS", price: 24075.0, note: "Equal lows forming - potential liquidity pool" }],
    confirmations: [],
    conflicts: [{ kind: "BOS", price: 24140.0, note: "Bearish BOS still active on internal structure" }],
    reasoningChain: [
      "Equal lows building below current price - a resting liquidity pool",
      "No sweep or reaction confirmed yet",
      "Internal structure is still bearish (BOS not yet reversed)",
    ],
    dataQuality: "MEDIUM",
    decision: "REVIEW",
  },
  {
    id: "sig-004",
    instrument: "BANKNIFTY",
    direction: "BULLISH",
    methodology: "SMC",
    state: "TARGET_HIT",
    score: 88,
    grade: "A",
    createdAt: minutesAgo(180),
    updatedAt: minutesAgo(95),
    entry: 50840.0,
    stopLoss: 50705.0,
    targets: [51050.0],
    riskReward: 1.6,
    coreSignal: [{ kind: "MSS", price: 50790.0 }],
    confirmations: [{ kind: "SWEEP", price: 50710.0, note: "Swept session low with rejection" }],
    conflicts: [],
    reasoningChain: [
      "Session low swept with a rejecting wick",
      "Bullish MSS confirmed on the next displacement leg",
      "Target reached cleanly, no retest required",
    ],
    dataQuality: "HIGH",
    decision: "MANUAL_ENTRY",
  },
  {
    id: "sig-005",
    instrument: "NIFTY",
    direction: "BEARISH",
    methodology: "SMC",
    state: "STOP_HIT",
    score: 63,
    grade: "B",
    createdAt: minutesAgo(240),
    updatedAt: minutesAgo(190),
    entry: 24205.0,
    stopLoss: 24248.0,
    targets: [24120.0],
    riskReward: 2.0,
    coreSignal: [{ kind: "CHOCH", price: 24215.0 }],
    confirmations: [{ kind: "ORDER_BLOCK_BEARISH", price: 24200.0 }],
    conflicts: [],
    reasoningChain: [
      "Bearish CHoCH confirmed at prior swing high",
      "Entry from bearish order block retest",
      "Structure failed - MSS never confirmed, stop hit on continuation higher",
    ],
    dataQuality: "MEDIUM",
    decision: "REVIEW",
  },
  {
    id: "sig-006",
    instrument: "BANKNIFTY",
    direction: "BULLISH",
    methodology: "SMC",
    state: "INVALIDATED",
    score: 41,
    grade: "C",
    createdAt: minutesAgo(70),
    updatedAt: minutesAgo(55),
    entry: null,
    stopLoss: null,
    targets: [],
    riskReward: null,
    coreSignal: [{ kind: "CHOCH", price: 50990.0 }],
    confirmations: [],
    conflicts: [{ kind: "CHOCH_FAILED", price: 51040.0, note: "Price reclaimed CHoCH bar's opposite extreme" }],
    reasoningChain: [
      "Bullish CHoCH candidate identified",
      "Price closed back beyond the CHoCH bar's opposite extreme before MSS confirmed",
      "Logged as CHoCH_FAILED - setup invalidated",
    ],
    dataQuality: "HIGH",
    decision: "REVIEW",
  },
  {
    id: "sig-007",
    instrument: "NIFTY",
    direction: "BEARISH",
    methodology: "SMC",
    state: "EXPIRED",
    score: 48,
    grade: "C",
    createdAt: minutesAgo(320),
    updatedAt: minutesAgo(260),
    entry: null,
    stopLoss: null,
    targets: [],
    riskReward: null,
    coreSignal: [{ kind: "EQUAL_HIGHS", price: 24260.0 }],
    confirmations: [],
    conflicts: [],
    reasoningChain: [
      "Equal highs identified as a resting liquidity pool",
      "No sweep occurred within the setup's validity window",
      "Signal expired without confirming",
    ],
    dataQuality: "LOW",
    decision: "REVIEW",
  },
];

export const MOCK_MARKET_OVERVIEW: MarketOverview[] = [
  { instrument: "NIFTY", lastPrice: 24127.65, changePct: 0.34, regime: "TRENDING", session: "MIDDAY" },
  { instrument: "BANKNIFTY", lastPrice: 51198.4, changePct: -0.21, regime: "VOLATILE", session: "MIDDAY" },
];

export const MOCK_SYSTEM_HEALTH: SystemHealth = {
  dataFeedConnected: true,
  lastTickAt: minutesAgo(0),
  telegramConfigured: true,
  automationEnabled: false,
};
